### ISSUE TITLE
0.4.0 support

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/era-compiler-vyper#77]
0.4.0 is a massive update to vyper, with imports!

https://github.com/vyperlang/vyper/releases

Could we support this?

**Comment by hedgar2017** [comment]
@PatrickAlphaC supported [here](https://github.com/matter-labs/era-compiler-vyper/blob/main/CHANGELOG.md#added)!

**Comment by PatrickAlphaC** [comment]
Let's go!!!
