### ISSUE TITLE
`assert UNREACHABLE` produces a `REVERT` instead of `INVALID` 

### ISSUE THREAD

**Issue by trocher** [matter-labs/era-compiler-vyper#83]
#### 📝 Description

In Vyper, both `assert test UNREACHABLE` and `raise UNREACHABLE` compile to the `INVALID` opcode, while the latter is the case for the era Vyper compiler, the former compiles to a `REVERT` opcode.

#### 🔄 Reproduction Steps

Deploying the following code and calling the function `foo()` returns  `[425, 413, 395, 10305]`.

```Vyper
GAS: constant(uint256) = 10000

@external
@payable
def foo() -> DynArray[uint256, 4]:
    values: DynArray[uint256, 4] = []
    if True:
        a1: uint256 = msg.gas
        ret: bool = raw_call(self, method_id("assert_()"), revert_on_failure=False, gas = GAS) 
        a2: uint256 = msg.gas
        assert not ret
        values.append(a1 - a2)
    if True:
        a1: uint256 = msg.gas
        ret: bool = raw_call(self, method_id("assert_unreachable()"), revert_on_failure=False, gas = GAS) 
        a2: uint256 = msg.gas
        assert not ret
        values.append(a1 - a2)
    if True:
        a1: uint256 = msg.gas
        ret: bool = raw_call(self, method_id("raise_()"), revert_on_failure=False, gas = GAS) 
        a2: uint256 = msg.gas
        assert not ret
        values.append(a1 - a2)
    if True:
        a1: uint256 = msg.gas
        ret: bool = raw_call(self, method_id("raise_unreachable()"), revert_on_failure=False, gas = GAS) 
        a2: uint256 = msg.gas
        assert not ret
        values.append(a1 - a2)
    return values

@external
def assert_():
    x:bool = False
    assert x
@external
def assert_unreachable():
    x:bool = False
    assert x, UNREACHABLE
    
@external
def raise_():
    raise

@external
def raise_unreachable():
    raise UNREACHABLE
```

#### 🤔 Expected Behavior

I would expect the second element of the array returned by `foo()` to be greater than `10000` given that `assert False UNREACHABLE` should burn all the gas passed to the context.

#### 😯 Current Behavior

the second element of the array returned by `foo()` is much smaller than `10000`, meaning that `assert False UNREACHABLE` did not consume all the gas passed to the function `assert_unreachable`.

#### 🖥️ Environment

`Vyper compiler for ZKsync v1.5.2 (LLVM build 280f38e3b73cbed0b037aa7e6c073d8e25dbdaa1)`, Vyper `0.10.0`
using `OSX`

#### 📋 Additional Context

https://github.com/matter-labs/era-compiler-vyper/blob/ceb0fb0f5a5f285b141f6c8ac92b34159913c121/src/project/contract/vyper/expression/instruction/mod.rs#L612-L613

**Comment by hedgar2017** [comment]
Thanks for the report!
The issue is clear. I'll fix it next week.

**Comment by hedgar2017** [comment]
The test added here: https://github.com/matter-labs/era-compiler-tests/pull/49
